### ISSUE TITLE
Reassigned keys for controls are not persistent across session

### ISSUE THREAD

**Issue by Galenmacil** [linuxgurugamer/EVAEnhancementsContinued#4]
You can change them in game using the EVAE interface but they reset to their default values when you quit and reload... Would be nice to be able to set them to whatever I prefer.

**Comment by linuxgurugamer** [comment]
It's missing a folder, create the following:
EVAEnhancements/PluginData

But there is still a problem.
I'll get it updated

**Comment by linuxgurugamer** [comment]
Fixed
