### ISSUE TITLE
[Feature Req] Add "turbo" mode to EVA

### ISSUE THREAD

**Issue by leatherneck6017** [linuxgurugamer/EVAEnhancementsContinued#5]
Similar to precision mode, except the opposite. I recently ran into a problem when trying to do repairs on my Minmus drill using KIS. I loaded up a KIS backpack container with a single gigantor solar panel. Once my Kerbal had the KIS container on his back he was unable to ascend via EVA. Couldn't jump either, but that's fine. It would be nice to have the option to make the EVA jetpack be able to go into overdrive, turbo mode for these fringe cases.

**Comment by linuxgurugamer** [comment]
Would be nice, but not going to do this, sorry.
